### ISSUE TITLE
作者您好，想请您开发一个项目

### ISSUE THREAD

**Issue by xiaoyuer0408** [cleverbao/AutoProxy#2]
您好，还请回复我一下谢谢

**Comment by ba0gu0** [comment]
> 您好，还请回复我一下谢谢

？？？

**Comment by xiaoyuer0408** [comment]
能不能给个联系方式详聊

**Comment by xiaoyuer0408** [comment]
> > 您好，还请回复我一下谢谢
> 
> ？？？

能不能回复一下作者

**Comment by ba0gu0** [comment]
> 能不能给个联系方式详聊

感谢关注哈，暂时没打算做第三方项目。

**Comment by xiaoyuer0408** [comment]
> > 能不能给个联系方式详聊
> 
> 
> 
> 感谢关注哈，暂时没打算做第三方项目。

在你现有上项目上改进就行，
